#!/usr/bin/zsh
#
# Set up for Yale Haskell 2.x users.
#

export PRELUDE=$HASKELL/progs/prelude
export HASKELL_LIBRARY=$HASKELL/progs/lib

# You may need to change this to point at the appropriate subdirectory,
# depending on which Lisp is being used.
#export PRELUDEBIN=$PRELUDE/lucid
export PRELUDEBIN=$PRELUDE/cmu

# You may need to change this to point at the appropriate subdirectory,
# depending on which Lisp is being used.
#setenv LIBRARYBIN=$HASKELL_LIBRARY/bin/lucid
export LIBRARYBIN=$HASKELL_LIBRARY/bin/cmu

# You may need to change this to point at the appropriate executable,
# depending on which Lisp is being used.
#export HASKELLPROG $HASKELL/bin/haskell
export HASKELLPROG=$HASKELL/bin/cmu-haskell

# You only need this next definition if you are using the CMU CL version
# of haskell and you have /tmp mounted on a tmpfs file system (it won't
# be able to initialize itself otherwise).
#export CMUCL_EMPTYFILE=/var/tmp/empty
